### ISSUE TITLE
A little help with routing for content

### ISSUE THREAD

**Issue by smeehan82** [smeehan82/Hermes.Clients.React#2]
Yo man I'm having an issue trying to route to my ContentDetails component.  It's probably something in my routing file but can you take a look and see if I'm doing something wrong?

**Comment by smeehan82** [comment]
So I updated my code for the content components to take the urlName and filter to the correct store and pull the pertinent data, i'm still keeping everything as IContent for the moment but I'm still missing something for the routing

**Comment by agrady42** [comment]
Turns out the problem was with the nested route - if you nest the route the router component will expect you to render the the component you want as a child of the parent route component (see how this works in the AppRoot component). We don't want that for content, so I fixed it in [a03c294](https://github.com/smeehan82/Hermes.Clients.React/commit/a03c29450b364248c911cf61ae6707f906444394)
